services:
  db:
    image: postgres:18.2-alpine # Specific versions are safer than 'latest'
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: tasks_manager
      POSTGRES_PASSWORD: tasks_manager
      POSTGRES_DB: tasks_manager
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data:
